USE DATABASE DATA_UNIFICATION_DB;
create schema bronze;
 
USE SCHEMA BRONZE;
CREATE OR REPLACE TABLE SAP_CUSTOMER_MASTER
(
    CUSTOMER_ID STRING,
    CUSTOMER_NAME STRING,
    EMAIL STRING,
    PHONE STRING,
    CITY STRING,
    STATE STRING,
    ZIP_CODE STRING,
    COUNTRY STRING,
    CUSTOMER_TYPE STRING,
 
    SOURCE_SYSTEM STRING,
 
    LOAD_TIMESTAMP TIMESTAMP,
 
    LAST_MODIFIED_DATE TIMESTAMP
);
 

 
CREATE OR REPLACE TABLE ORACLE_CUSTOMERS
(
    CUSTOMER_ID STRING,
    CUSTOMER_NAME STRING,
    EMAIL STRING,
    PHONE STRING,
    CITY STRING,
    STATE STRING,
    ZIP_CODE STRING,
    COUNTRY STRING,
    CUSTOMER_TYPE STRING,
 
    SOURCE_SYSTEM STRING,
 
    LOAD_TIMESTAMP TIMESTAMP,
 
    LAST_MODIFIED_DATE TIMESTAMP
);
 

 
 
CREATE OR REPLACE TABLE SALESFORCE_ACCOUNTS
(
    CUSTOMER_ID STRING,
    CUSTOMER_NAME STRING,
    EMAIL STRING,
    PHONE STRING,
    CITY STRING,
    STATE STRING,
    ZIP_CODE STRING,
    COUNTRY STRING,
    CUSTOMER_TYPE STRING,
 
    SOURCE_SYSTEM STRING,
 
    LOAD_TIMESTAMP TIMESTAMP,
 
    LAST_MODIFIED_DATE TIMESTAMP
);
 

 
 
CREATE OR REPLACE VIEW ALL_CUSTOMERS AS
 
SELECT * FROM SAP_CUSTOMER_MASTER
 
UNION ALL
 
SELECT * FROM ORACLE_CUSTOMERS
 
UNION ALL
 
SELECT * FROM SALESFORCE_ACCOUNTS;
 
 
SELECT *
FROM ALL_CUSTOMERS
LIMIT 200;