
create or replace database DATA_UNIFICATION_DB; 

use database DATA_UNIFICATION_DB;
 
CREATE OR REPLACE SCHEMA DATA_UNIFICATION_DB.RAW_STG;
 
use schema raw_stg;
 
CREATE OR REPLACE TABLE SAP_CUSTOMERS_STG
(
    KUNNR STRING,
    NAME1 STRING,
    NAME2 STRING,
    CITY STRING,
    STATE STRING,
    POST_CODE STRING,
    TELF1 STRING,
    SMTP_ADDR STRING,
    COUNTRY STRING,
    CUSTOMER_GROUP STRING,
    CREATED_DATE DATE
);
 
 
 
CREATE OR REPLACE TABLE ORACLE_CUSTOMERS_STG
(
    PARTY_ID STRING,
    CUSTOMER_NAME STRING,
    CITY STRING,
    STATE STRING,
    ZIP_CODE STRING,
    PHONE_NUMBER STRING,
    EMAIL_ADDRESS STRING,
    COUNTRY STRING,
    CUSTOMER_CATEGORY STRING,
    CREATION_DATE DATE
    
);

CREATE OR REPLACE TABLE SALESFORCE_CUSTOMERS_STG
(
    ACCOUNT_ID STRING,
    ACCOUNT_NAME STRING,
    BILLING_CITY STRING,
    STATE STRING,
    PHONE STRING,
    EMAIL STRING,
    COUNTRY STRING,
    ACCOUNT_TYPE STRING,
    CREATED_DATE DATE
);


create or replace stage customer_stage;






CREATE OR REPLACE FILE FORMAT DATA_UNIFICATION_DB.raw_stg.CSV_FORMAT
TYPE = CSV
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
SKIP_HEADER = 1;



 
COPY INTO SAP_CUSTOMERS_STG
FROM @CUSTOMER_STAGE/SAP_CUSTOMER_MASTER.csv
FILE_FORMAT = 'DATA_UNIFICATION_DB.RAW_STG.CSV_FORMAT'
ON_ERROR='CONTINUE';

COPY INTO ORACLE_CUSTOMERS_STG
FROM @CUSTOMER_STAGE/ORACLE_CUSTOMERS.csv
FILE_FORMAT = 'DATA_UNIFICATION_DB.RAW_STG.CSV_FORMAT'
ON_ERROR='CONTINUE';

COPY INTO SALESFORCE_CUSTOMERS_STG
FROM @CUSTOMER_STAGE/SALESFORCE_ACCOUNTS.csv
FILE_FORMAT = 'DATA_UNIFICATION_DB.RAW_STG.CSV_FORMAT'
ON_ERROR='CONTINUE';
 
 
select * from SAP_CUSTOMERS_STG;

select * from SALESFORCE_CUSTOMERS_STG;

select * from oracle_customers_stg;



 